theme: jekyll-theme-slate
title:  CNM Libraries
description:  CNM Libraries is a beacon for learning and innovation in a collaborative environment where individual freedom and social responsiblity flourish and the college-wide vision of Changing Lives and Building Community is honored and enhanced.
